name: Remote Windows PC Automation

on:
  push:
    branches:
      - main

jobs:
  create-dummy-file:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure TrustedHosts
        run: |
          Set-Item WSMan:\localhost\Client\TrustedHosts -Value "${{ secrets.REMOTE_HOST }}"
        shell: pwsh

      - name: Create dummy.txt on remote Windows PC
        run: |
          $remoteComputer = "${{ secrets.REMOTE_HOST }}"
          $remoteUser = "${{ secrets.REMOTE_USER }}"
          $remotePassword = "${{ secrets.REMOTE_PASSWORD }}"
          $securePassword = ConvertTo-SecureString $remotePassword -AsPlainText -Force
          $credential = New-Object System.Management.Automation.PSCredential ($remoteUser, $securePassword)
          $sessionOption = New-PSSessionOption -SkipCACheck -SkipCNCheck -SkipRevocationCheck
          $session = New-PSSession -ComputerName $remoteComputer -Credential $credential -UseSSL -SessionOption $sessionOption
          Invoke-Command -Session $session -ScriptBlock {
              New-Item -Path "C:\path\to\directory\dummy.txt" -ItemType File -Force
          }
          Remove-PSSession -Session $session
        shell: pwsh
