name: Create Dummy File on Remote PC

on:
  push:
    branches:
      - develop

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create dummy.txt on remote Windows PC
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_PASSWORD }}
          password: ${{ secrets.REMOTE_USER }}
          script: |
            echo "This is a dummy file" > C:\LamaSoftware\vlah-test\dummy.txt
