name: Remote Windows PC Automation

on:
  push:
    branches:
      - main

jobs:
  create-dummy-file:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create dummy.txt on remote Windows PC
        run: |
          $remoteComputer = "${{ secrets.REMOTE_HOST }}"
          $remoteUser = "${{ secrets.REMOTE_USER }}"
          $remotePassword = "${{ secrets.REMOTE_PASSWORD }}"
          $securePassword = ConvertTo-SecureString $remotePassword -AsPlainText -Force
          $credential = New-Object System.Management.Automation.PSCredential ($remoteUser, $securePassword)
          Invoke-Command -ComputerName $remoteComputer -Credential $credential -ScriptBlock {
              New-Item -Path "C:\LamaSoftware\vlah-test\dummy.txt" -ItemType File -Force
          }
        shell: pwsh
